name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Functional-JavaScript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ddev/github-action-setup-ddev@v1

      - name: Install dependencies
        run: ddev composer install

      - name: Configure tests
        run: cp .github/workflows/phpunit.xml core/phpunit.xml

      - name: Run one test
        run: ddev exec SYMFONY_DEPRECATIONS_HELPER=weak phpunit -c core --verbose --fail-on-incomplete --fail-on-risky --fail-on-skipped core/modules/block/tests/src/FunctionalJavascript/BlockAddTest.php
